name: Docker Image CI

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build ./ -t mmakilan/ssi-monitoring-fe:latest

      - name: Push Image to DockerHub
        run: |
          docker login -u mmakilan -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push mmakilan/ssi-monitoring-fe:latest
