name: Docker Image CI

on:
  push:
    branches: [ "layout" ]
  pull_request:
    branches: [ "layout" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag monitoring-app-fe:$(date +%s)
